sudo : required

services:
    - docker

before_install:
    - docker build chrisjerry9618/docker-react -f Dockerfile.dev .

script :
    - docker run -e CI=true chrisjerry/docker-react npm run test -- --coverage

language : generic
