sudo : required

services:
    - docker

before_install:
    - docker build -t chrisjerry9618/docker-react -f Dockerfile.dev .

script :
    - docker run chrisjerry/docker-react npm run test -- --coverage
