sudo : required

services:
    - docker

before_install:
    - docker build -t chrisjerry9618/docker-react -f Dockerfile.dev .

script :
    - docker run -e CI=true chrisjerry9618/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region : "us-east-1"
    app: "Docker-react"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-846467755765"
    bucket_path: "Docker-react"
    on:
        branch : master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KE
language : generic
